name: petclinic Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests mvn
      run: mvn package
    - name: Build & Push images
      run: |
        docker login --username=bouchtateam --password=${PASSDOCKERHUB}
        docker image build -t bouchtateam/petclinicgitops:v1 .
        docker push bouchtateam/petclinicgitops:v1
